import Head from 'next/head';
import Container from '../../layout/Container';
import Ball from '../../components/Ball';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Ball animationChoice='slide'/>
        <Ball animationChoice='fade'/>
      </Container>
    </>
  )
}
